### PR TITLE
Fix the not-really-clean <hr> post separators

### PR DESCRIPTION
**Pull request by davclark**
This theme is so close to perfect! This last change cleans up one of the only "problems" (DIVIDER is "" until it is assigned). Specifically, this change solves the problem of an extra \<hr> after the final post in the index.

### CODE REVIEW

**Comment by davidtmiller** [comment]
That divider is intentional since it's the separation between the main content of the page and the footer.

**Comment by davidtmiller** [comment]
At least I think it was...I'll have to look into this.

**Comment by davclark** [comment]
Ah! I see I created this problem in my own site (as I am using a paginator in an "archive" - the front page is for upcoming events). You can see the "older posts" button in your version here:

http://ironsummitmedia.github.io/startbootstrap-clean-blog-jekyll/

So, nevermind. The design was perfect. Thanks for making it - it's a joy to see folks making such a well architected theme!

**Comment by davidtmiller** [comment]
No problem, thanks for checking it out! Have a good day!

**Pull request closed without merging**
